### PR TITLE
adjust to removed extra argument from AdapterInterface

### PR DESCRIPTION
**Pull request by dbu**
adjust to https://github.com/symfony-cmf/routing-auto/pull/100

restart build once the routing-auto PR is merged and RC3 tagged.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
now it is consistently broken :-)

**Comment by dbu** [comment]
fixed the mistakes in the PR, now we only have those left that happened on master before too.

**Comment by ElectricMaxxx** [comment]
I restarted the build, hoping it was the doctrine-odm. But the errors are still there @dantleech @wouterj any chance to fix that?

**Comment by ElectricMaxxx** [comment]
@dbu @dantleech I think i found the problem, but without knowing why:

there was a change for `jms/serializer` from `1.5.*` to `^1.5`, which also allows `1.6`, on `routing-auto`. I get to that issue, as i tried to require `symfony-cmf/routing-auto:2.0.0-RC1`, cause i whanted to see the former behavior. That said i had to fix `jms/serializer` to `1.5.0`. And then ... The tests are green.

So we should revert the `jms/serializer` dependency change on `routing-auto`, release and this will be green, or somebody knows what the change in serializer had been?

**Comment by ElectricMaxxx** [comment]
I should work with the branch first, for next time.

**Comment by ElectricMaxxx** [comment]
I have no idea anymore :-( i had it working and running localy with `jms/metada:1.5.0` and `symfony-cmf/routing-auto:2.0.0-RC1` but ther is no other change on RC2 then the jms change.

**Comment by ElectricMaxxx** [comment]
i work on in https://github.com/symfony-cmf/routing-auto-bundle/pull/210

**Pull request closed without merging**
